// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANci5BFSCwkkuxBscfUiHrSmo-b7nS9Uc',
    appId: '1:678159510040:web:27e927cb48fe139a4db16d',
    messagingSenderId: '678159510040',
    projectId: 'asistencia-vial-quito',
    authDomain: 'asistencia-vial-quito.firebaseapp.com',
    storageBucket: 'asistencia-vial-quito.firebasestorage.app',
    measurementId: 'G-C4MKJQ6LPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB26zwBIVvaRhPTralw4XFNfrjtCe8zJQ',
    appId: '1:678159510040:android:fb927eca3db97c554db16d',
    messagingSenderId: '678159510040',
    projectId: 'asistencia-vial-quito',
    storageBucket: 'asistencia-vial-quito.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFiUN1V7Ahk_IJ-o0iJutIgERmTYtikLw',
    appId: '1:678159510040:ios:5d15b38016f3d1914db16d',
    messagingSenderId: '678159510040',
    projectId: 'asistencia-vial-quito',
    storageBucket: 'asistencia-vial-quito.firebasestorage.app',
    iosBundleId: 'com.example.asitenteVial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFiUN1V7Ahk_IJ-o0iJutIgERmTYtikLw',
    appId: '1:678159510040:ios:5d15b38016f3d1914db16d',
    messagingSenderId: '678159510040',
    projectId: 'asistencia-vial-quito',
    storageBucket: 'asistencia-vial-quito.firebasestorage.app',
    iosBundleId: 'com.example.asitenteVial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANci5BFSCwkkuxBscfUiHrSmo-b7nS9Uc',
    appId: '1:678159510040:web:f63560ff5fb2623e4db16d',
    messagingSenderId: '678159510040',
    projectId: 'asistencia-vial-quito',
    authDomain: 'asistencia-vial-quito.firebaseapp.com',
    storageBucket: 'asistencia-vial-quito.firebasestorage.app',
    measurementId: 'G-K5LPCNBYW6',
  );
}
